services:
  the_return_of_api:
    build: CuatroApiPracticas
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgresql-service:5432/jpaApi4?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USERNAME: postgres
      DB_PASSWORD: barcelona2009
    restart: always
    depends_on:
      postgresql-service:
          condition: service_healthy
  postgresql-service:
    image: postgres:16 
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: barcelona2009
      POSTGRES_DB: jpaApi4
      POSTGRES_USER: postgres
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10